version: '3'
services:
  postgres:
    image: postgres:9.6
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=traveling
      - POSTGRES_PASSWORD=traveling
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
